---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: text-printer
  name: text-printer
spec:
  containers:
  - image: busybox
    name: text-printer
    command:
      - '/bin/sh'
      - '-c'
      - 'while true; do echo "Environment VAR: $COLOR"; sleep 60; done'
    env:
    - name: COLOR
      value: "RED"
...
