apiVersion: v1
kind: Namespace
metadata:
  name: amber
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-amber
  namespace: amber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-amber
  template:
    metadata:
      labels:
        app: sleep-amber
    spec:
      containers:
      - name: sleep-amber
        image: curlimages/curl
        command: ["/bin/sh", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "10m"
            memory: "64Mi"
---
