apiVersion: v1
kind: Namespace
metadata:
  name: orange
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: orange
  labels:
    app: sidecar-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        cpu: "10m"
        memory: "64Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: no-sidecar-pod
  namespace: orange
  labels:
    app: no-sidecar-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        cpu: "10m"
        memory: "64Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: sidecar-service
  namespace: orange
spec:
  selector:
    app: sidecar-pod
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
  type: ClusterIP
