---
apiVersion: v1
kind: Namespace
metadata:
  name: bronze
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep-bronze
  namespace: bronze
  labels:
    app: sleep-bronze
spec:
  containers:
  - name: sleep-bronze
    image: curlimages/curl
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "10m"
        memory: "64Mi"
