apiVersion: v1
kind: Namespace
metadata:
  name: indigo
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep-indigo
  namespace: indigo
  labels:
    app: sleep-indigo
spec:
  containers:
  - name: sleep-indigo
    image: curlimages/curl
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "10m"
        memory: "64Mi"
---
