---
apiVersion: v1
kind: Namespace
metadata:
  name: red
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: echo-red
  namespace: red
  labels:
    app: echo-red
spec:
  containers:
  - name: echo-red
    image: viktoruj/cks-lab:ica_echo_version_app_v1
    env:
    - name: VERSION
      value: "v1"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "10m"
        memory: "32Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep-red
  namespace: red
  labels:
    app: sleep-red
spec:
  containers:
  - name: sleep-red
    image: curlimages/curl
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "10m"
        memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-red
  namespace: red
  labels:
    app: echo-red
spec:
  selector:
    app: echo-red
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
