controller:
  config:
    enable-snippet-annotations: "true"
    allow-snippet-annotations: "true"
    ssl-redirect: "false"
    force-ssl-redirect: "false"
  service:
    type: NodePort
    nodePorts:
      http: 30102
      https: 31139
  ingressClass:
    create: true
    name: nginx
    setAsDefaultIngress: true
