apiVersion: v1
kind: Namespace
metadata:
  name: secure
  labels:
    name: secure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secure
  name: secure
  namespace: secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure
  strategy: {}
  template:
    metadata:
      labels:
        app: secure
    spec:
      containers:
      - image: viktoruj/ping_pong:alpine
        name: c1
      - image: viktoruj/ping_pong:alpine
        name: c2
      - image: viktoruj/ping_pong:alpine
        name: c3

