apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: prod-db
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---

apiVersion: v1
kind: Namespace
metadata:
  name: stage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name:  db
  namespace: prod-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: viktoruj/ping_pong:alpine
        name: db
        env:
          - name: SERVER_NAME
            value: "mysql"
          - name: SRV_PORT
            value: "3306"
        resources:
          requests:
            cpu:  "50m"
            memory: "10Mi"
        ports:
        - containerPort: 3306

