---
apiVersion: v1
kind: Namespace
metadata:
  name: team-xxx
  labels:
    name: team-xxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment1
  name: deployment1
  namespace: team-xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  strategy: {}
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
      - image: viktoruj/ping_pong:b7a1494-arm64-alpine  # pkg:apk/alpine/ca-certificates-bundle@20250619-r0?arch=aarch64"
        name: app1
        command: ["sleep", "1000000"]
      - image: viktoruj/ping_pong:f23606e-arm64-alpine  # referenceLocator": "pkg:apk/alpine/ca-certificates-bundle@20230506-r0?arch=aarch64",
        name: app2
        command: ["sleep", "1000000"]
      - image: viktoruj/ping_pong:53833ea-amd64-alpine # "pkg:apk/alpine/ca-certificates-bundle@20230506-r0?arch=x86_64"
        name: app3
        command: ["sleep", "1000000"]